### ISSUE TITLE
Insecure password-handling in mod_auth_sqlite

### ISSUE THREAD

**Issue by makefu** [janvidar/uhub#70]
Currently the uhub module `mod_auth_sqlite` stores all user passwords in plaintext. It would be advisable to use a common hashing scheme such as sha256 and salt to avoid having these passwords clear in the database.

Cheers!

**Comment by janvidar** [comment]
Yes - I agree, that would be ideal.

However, a one-way hash does not work technically with the ADC protocol.
It is simply not designed for this. - And yes, that's stupid!

So, the best thing we can really do is to encrypt with a symmetric cipher.

**Comment by tehnick** [comment]
> However, a one-way hash does not work technically with the ADC protocol.
> It is simply not designed for this.

Sorry, but could you describe why does hub need to know a real password? Why it cannot just calc hash from password sent by client and compare it with hash in database (which had been saved during registration on hub)?

**Comment by janvidar** [comment]
Sure,

The hub issues a challenge to the client in order to authenticate the user.

This is a GPA message (get password):
https://adc.sourceforge.io/ADC.html#_gpa

Which needs to be answered by the client with the PAS message.
https://adc.sourceforge.io/ADC.html#_pas

The Hub's GPA message comes with "random data", which in crypto lingo is a "nonce". (This nonce should only be used once in order to prevent replay attacks.)

The client concatenates the secret password with the "nonce" from the server and hashes this with the protocol hash which is auto-negotiated between client/hub at connection (typically TIGR).

This hashed data is sent back to the hub for verification. The hub therefore needs to know the plaintext password to be able to verify that the hashed data matches.

So, password is hashed like this:

HASHED_PASSWORD = HASH(password + nonce)

A more correct implementation would probably be:

HASHED_PASSWORD = HASH(HASH(password) + nonce)

... but this cannot be achieved at this point without changes to both clients and hubs. This also needs additional specification of hashes to be used for this purpose.

**Comment by makefu** [comment]
@janvidar thanks for clearing that up. So unfortunately there is no easy way to solve this because the server needs to know the plain text of the user password according to the ADC protocol.
That is quite unfortunate.
A symmetric cipher should work, however due to the fact that the server still would need to know the key when starting up and when new users authenticate with the server it is somewhat pointless.
